In [1]:
import sys
import numpy as np
sys.path.append('../surfinpy/')
import p_vs_t as pt
import phaseplot as pp
import utils as ut

bulk = {'M' : 1, 'O' : 2, 'Energy' : -781.954938, 'F-Units' : 4}
stoich = {'M': 24, 'X': 48, 'Y': 0, 'Area': 60.22, 'Energy': -535.660075, 'Label': '0.00 - $Ce^{4+}$'}
H2O = {'M': 24, 'X': 48, 'Y': 2, 'Area': 60.22, 'Energy': -621.877140,  'Label': '1.66 - $Ce^{4+}$'}
H2O_2 = {'M': 24, 'X': 48, 'Y': 4, 'Area': 60.22, 'Energy': -670.229520, 'Label': '3.32 - $Ce^{4+}$'}
data = [H2O, H2O_2]

surfs = ut.System(data, stoich)

In [2]:
coverage = surfs.calculate_coverage(1) 
    
print(coverage)

3.3211557622052475e+18


In [16]:
import numpy as np
val_arr = np.arange(30).reshape(10,3)
val_arr = val_arr * 3.3
print(val_arr.shape)

z_indices = np.array([1,0,2,1,0,2,1,0,2,1])
print(z_indices.shape)
x = val_arr[z_indices]
#x = z_indices.choose(val_arr)
print(x)

(10, 3)
(10,)
[[ 9.9 13.2 16.5]
 [ 0.   3.3  6.6]
 [19.8 23.1 26.4]
 [ 9.9 13.2 16.5]
 [ 0.   3.3  6.6]
 [19.8 23.1 26.4]
 [ 9.9 13.2 16.5]
 [ 0.   3.3  6.6]
 [19.8 23.1 26.4]
 [ 9.9 13.2 16.5]]
